const state={query:'',category:'',availability:'',sort:'name',visible:24};
const $=s=>document.querySelector(s), grid=$('#grid');
const money=n=>`AED ${Number(n).toFixed(2)}`;
const initials=name=>name.replace(/[^A-Za-z ]/g,'').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'•';
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function matches(){let p=PRODUCTS.filter(x=>{let hay=[x.id,x.sku,x.name,x.category,x.subCategory].join(' ').toLowerCase();return(!state.query||hay.includes(state.query))&&(!state.category||x.category===state.category)&&(!state.availability||x.status===state.availability)});return p.sort((a,b)=>state.sort==='saleLow'?a.salePrice-b.salePrice:state.sort==='saleHigh'?b.salePrice-a.salePrice:a.name.localeCompare(b.name))}
function render(){let p=matches(), show=p.slice(0,state.visible);$('#resultCount').textContent=`${p.length} product${p.length===1?'':'s'} found`;$('#clear').hidden=!(state.query||state.category||state.availability);grid.innerHTML=show.map(x=>`<article class="card" tabindex="0" data-id="${esc(x.key)}"><div class="art">${esc(initials(x.name))}</div><div class="card-body"><span class="tag">${esc(x.category)}</span><span class="stock ${x.status==='ACTIVE'?'':'out'}">${x.status==='ACTIVE'?'IN STOCK':'OUT OF STOCK'}</span><h3>${esc(x.name)}</h3><div class="prices">${money(x.salePrice)} ${x.price!==x.salePrice?`<span class="old">${money(x.price)}</span>`:''}</div></div></article>`).join('')||'<p>No products match those filters.</p>';$('#loadMore').hidden=show.length>=p.length;}
function detail(key){let x=PRODUCTS.find(p=>p.key===key);if(!x)return;$('#productDetail').innerHTML=`<div class="detail"><div class="art">${esc(initials(x.name))}</div><div class="detail-body"><p class="eyebrow">${esc(x.category)} · ${esc(x.subCategory)}</p><h2>${esc(x.name)}</h2><div class="prices">${money(x.salePrice)} ${x.price!==x.salePrice?`<span class="old">${money(x.price)}</span>`:''}</div><div class="facts"><div>Product ID<strong>${esc(x.id)}</strong></div><div>Offer SKU<strong>${esc(x.sku)}</strong></div><div>Availability<strong>${x.status==='ACTIVE'?'In stock':'Out of stock'}</strong></div><div>Condition<strong>${esc(x.condition)}</strong></div></div></div></div>`;$('#productDialog').showModal();history.replaceState(null,'','#product-'+encodeURIComponent(key));}
$('#search').addEventListener('input',e=>{state.query=e.target.value.toLowerCase().trim();state.visible=24;render()});['category','availability','sort'].forEach(k=>$('#'+k).addEventListener('change',e=>{state[k]=e.target.value;state.visible=24;render()}));
grid.addEventListener('click',e=>{let c=e.target.closest('.card');if(c)detail(c.dataset.id)});grid.addEventListener('keydown',e=>{let c=e.target.closest('.card');if(c&&(e.key==='Enter'||e.key===' ')){e.preventDefault();detail(c.dataset.id)}});$('#loadMore').onclick=()=>{state.visible+=24;render()};$('#clear').onclick=()=>{state.query=state.category=state.availability='';$('#search').value='';$('#category').value='';$('#availability').value='';state.visible=24;render()};$('#filtersButton').onclick=()=>{let f=$('#filters'),open=f.hasAttribute('hidden');f.toggleAttribute('hidden',!open);$('#filtersButton').setAttribute('aria-expanded',open)};$('#productDialog').querySelector('.close').onclick=()=>{$('#productDialog').close();history.replaceState(null,'','#catalogue')};
[...new Set(PRODUCTS.map(x=>x.category))].sort().forEach(c=>$('#category').insertAdjacentHTML('beforeend',`<option value="${esc(c)}">${esc(c)}</option>`));$('#year').textContent=new Date().getFullYear();render();let hash=decodeURIComponent(location.hash.replace('#product-',''));if(location.hash.startsWith('#product-'))detail(hash);
