const state={query:'',category:'',availability:'',sort:'name',visible:24};
const $=s=>document.querySelector(s), grid=$('#grid');
const money=n=>`AED ${Number(n).toFixed(2)}`;
const initials=name=>name.replace(/[^A-Za-z ]/g,'').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'•';
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function matches(){let p=PRODUCTS.filter(x=>{let hay=[x.id,x.sku,x.name,x.category,x.subCategory].join(' ').toLowerCase();return(!state.query||hay.includes(state.query))&&(!state.category||x.category===state.category)&&(!state.availability||x.status===state.availability)});return p.sort((a,b)=>state.sort==='saleLow'?a.salePrice-b.salePrice:state.sort==='saleHigh'?b.salePrice-a.salePrice:a.name.localeCompare(b.name))}
function art(x){return x.imageUrl?`<img src="${esc(x.imageUrl)}" alt="${esc(x.name)}" loading="lazy" onerror="this.replaceWith(Object.assign(document.createElement('div'),{className:'art',textContent:'${esc(initials(x.name))}'}))">`:`<div class="art">${esc(initials(x.name))}</div>`}
function render(){let p=matches(), show=p.slice(0,state.visible);$('#resultCount').textContent=`${p.length} product${p.length===1?'':'s'} found`;$('#clear').hidden=!(state.query||state.category||state.availability);grid.innerHTML=show.map(x=>`<article class="card" tabindex="0" data-id="${esc(x.key)}">${art(x)}<div class="card-body"><span class="tag">${esc(x.category)}</span><span class="stock ${x.status==='ACTIVE'?'':'out'}">${x.status==='ACTIVE'?'IN STOCK':'OUT OF STOCK'}</span><h3>${esc(x.name)}</h3><div class="prices">${money(x.salePrice)} ${x.price!==x.salePrice?`<span class="old">${money(x.price)}</span>`:''}</div></div></article>`).join('')||'<p>No products match those filters.</p>';$('#loadMore').hidden=show.length>=p.length;}
function detail(key){let x=PRODUCTS.find(p=>p.key===key);if(!x)return;$('#productDetail').innerHTML=`<div class="detail">${art(x)}<div class="detail-body"><p class="eyebrow">${esc(x.category)} · ${esc(x.subCategory)}</p><h2>${esc(x.name)}</h2><div class="prices">${money(x.salePrice)} ${x.price!==x.salePrice?`<span class="old">${money(x.price)}</span>`:''}</div><div class="facts"><div>Product ID<strong>${esc(x.id)}</strong></div><div>Offer SKU<strong>${esc(x.sku)}</strong></div><div>Availability<strong>${x.status==='ACTIVE'?'In stock':'Out of stock'}</strong></div><div>Condition<strong>${esc(x.condition)}</strong></div></div>${x.status==='ACTIVE'?`<button class="add-cart" data-key="${esc(x.key)}">Add to cart</button>`:''}</div></div>`;$('#productDialog').showModal();history.replaceState(null,'','#product-'+encodeURIComponent(key));}
$('#search').addEventListener('input',e=>{state.query=e.target.value.toLowerCase().trim();state.visible=24;render()});['category','availability','sort'].forEach(k=>$('#'+k).addEventListener('change',e=>{state[k]=e.target.value;state.visible=24;render()}));
grid.addEventListener('click',e=>{let c=e.target.closest('.card');if(c)detail(c.dataset.id)});grid.addEventListener('keydown',e=>{let c=e.target.closest('.card');if(c&&(e.key==='Enter'||e.key===' ')){e.preventDefault();detail(c.dataset.id)}});$('#loadMore').onclick=()=>{state.visible+=24;render()};$('#clear').onclick=()=>{state.query=state.category=state.availability='';$('#search').value='';$('#category').value='';$('#availability').value='';state.visible=24;render()};$('#filtersButton').onclick=()=>{let f=$('#filters'),open=f.hasAttribute('hidden');f.toggleAttribute('hidden',!open);$('#filtersButton').setAttribute('aria-expanded',open)};$('#productDialog').querySelector('.close').onclick=()=>{$('#productDialog').close();history.replaceState(null,'','#catalogue')};
[...new Set(PRODUCTS.map(x=>x.category))].sort().forEach(c=>$('#category').insertAdjacentHTML('beforeend',`<option value="${esc(c)}">${esc(c)}</option>`));$('#year').textContent=new Date().getFullYear();render();let hash=decodeURIComponent(location.hash.replace('#product-',''));if(location.hash.startsWith('#product-'))detail(hash);
const cart=[];
function renderCart(){let total=cart.reduce((sum,item)=>sum+item.product.salePrice*item.quantity,0);$('#cartCount').textContent=cart.reduce((sum,item)=>sum+item.quantity,0);$('#cartTotal').textContent=money(total);$('#cartItems').innerHTML=cart.length?cart.map(item=>`<div class="cart-item"><h3>${esc(item.product.name)}</h3><strong>${money(item.product.salePrice*item.quantity)}</strong><div class="quantity-controls"><button data-action="minus" data-key="${item.product.key}">−</button><span>${item.quantity}</span><button data-action="plus" data-key="${item.product.key}">+</button><button class="remove" data-action="remove" data-key="${item.product.key}">Remove</button></div></div>`).join(''):'<p class="empty-cart">Your cart is empty.</p>';}
function addCart(key){let product=PRODUCTS.find(p=>p.key===key),item=cart.find(x=>x.product.key===key);if(!product)return;if(item)item.quantity++;else cart.push({product,quantity:1});renderCart();}
function openCart(){renderCart();$('#cartPanel').classList.add('open');$('#cartShade').hidden=false}function closeCart(){$('#cartPanel').classList.remove('open');$('#cartShade').hidden=true}
$('#productDetail').addEventListener('click',e=>{let b=e.target.closest('.add-cart');if(b){addCart(b.dataset.key);$('#productDialog').close();openCart();}});$('#cartButton').onclick=openCart;$('#cartClose').onclick=closeCart;$('#cartShade').onclick=closeCart;
$('#cartItems').addEventListener('click',e=>{let b=e.target.closest('button[data-action]');if(!b)return;let i=cart.findIndex(x=>x.product.key===b.dataset.key);if(i<0)return;if(b.dataset.action==='plus')cart[i].quantity++;if(b.dataset.action==='minus')cart[i].quantity--;if(b.dataset.action==='remove'||cart[i].quantity<1)cart.splice(i,1);renderCart();});
$('#whatsappOrder').onclick=()=>{if(!cart.length)return;let lines=cart.map(x=>`• ${x.product.name} (${x.product.id}) × ${x.quantity} — ${money(x.product.salePrice*x.quantity)}`);let total=cart.reduce((s,x)=>s+x.product.salePrice*x.quantity,0);let text=`Hello, I would like to order:\n\n${lines.join('\n')}\n\nTotal: ${money(total)}`;window.open('https://wa.me/971562469500?text='+encodeURIComponent(text),'_blank');};
